// Code generated by Slice Machine. DO NOT EDIT.

import CtaContentImage from './CtaContentImage/index.svelte';
import Hero from './Hero/index.svelte';
import MinimalHeader from './MinimalHeader/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	cta_content_image: CtaContentImage,
	hero: Hero,
	minimal_header: MinimalHeader,
	rich_text: RichText
};
