// Code generated by Slice Machine. DO NOT EDIT.

import AwardLogoSection from './AwardLogoSection/index.svelte';
import CenteredCta from './CenteredCta/index.svelte';
import CoreValues from './CoreValues/index.svelte';
import CtaContentImage from './CtaContentImage/index.svelte';
import Hero from './Hero/index.svelte';
import MinimalHeader from './MinimalHeader/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	award_logo_section: AwardLogoSection,
	centered_cta: CenteredCta,
	core_values: CoreValues,
	cta_content_image: CtaContentImage,
	hero: Hero,
	minimal_header: MinimalHeader,
	rich_text: RichText
};
